#!/usr/bin/env bash
# Build the reviewer agents in .claude/agents/ from the ECC plugin's agents plus
# this repo's context.
#
# Why vendored: cloud sessions do not load plugins, so the reviewers that
# /work-next-item Step 6.5 launches must be committed to the repo. Each agent is
# ECC's file verbatim, frontmatter and body, with a "Repo context" block after
# the frontmatter that overrides generic advice that does not fit this repo.
#
# The agents to build are the files in .claude/agent-context/: <agent>.md holds
# that agent's context, and _common.md goes before it in every agent. To add an
# agent, add its context file (named as in ECC's agents/ directory) and re-run.
# Edit the context files, never the generated agents.
#
# Usage (from anywhere in the repo): scripts/vendor-agents.sh
#   ECC_ROOT  a clone of https://github.com/affaan-m/ECC
#             (default: Claude Code's checkout of the ECC plugin)
# Then review `git diff .claude/agents/`: an upstream change arrives verbatim.
set -euo pipefail

ECC_ROOT="${ECC_ROOT:-$HOME/.claude/plugins/marketplaces/ecc}"
DEST=.claude/agents
CONTEXT=.claude/agent-context
COMMON="$CONTEXT/_common.md"

die() { echo "vendor-agents: $*" >&2; exit 1; }

root="$(git rev-parse --show-toplevel 2>/dev/null)" || die "not inside a git repository"
cd "$root"
[ -d "$ECC_ROOT/agents" ] || die "no ECC agents at $ECC_ROOT/agents (set ECC_ROOT to a clone of https://github.com/affaan-m/ECC)"
[ -f "$ECC_ROOT/LICENSE" ] || die "no LICENSE in $ECC_ROOT; vendoring needs it to ship beside the agents"
[ -f "$COMMON" ] || die "missing $COMMON"
sha="$(git -C "$ECC_ROOT" rev-parse HEAD 2>/dev/null)" || die "$ECC_ROOT is not a git checkout, so the vendored commit is unknown"

agents=()
for f in "$CONTEXT"/*.md; do
  [ -e "$f" ] || continue
  name="$(basename "$f" .md)"
  [ "$name" = _common ] || agents+=("$name")
done
[ "${#agents[@]}" -gt 0 ] || die "no agent context files in $CONTEXT (add <agent>.md for each reviewer)"

# Check every agent before writing any, so a typo cannot leave a half-updated set.
for a in "${agents[@]}"; do
  src="$ECC_ROOT/agents/$a.md"
  [ -f "$src" ] || die "ECC has no agent named '$a' (from $CONTEXT/$a.md)"
  [ "$(head -1 "$src")" = --- ] || die "$src has no frontmatter"
done

# Upstream file, with the attribution and context inserted after the frontmatter.
build() {
  local a="$1"
  awk -v a="$a" -v sha="$sha" -v common="$COMMON" -v ctx="$CONTEXT/$a.md" '
    function emit(file,   line) { while ((getline line < file) > 0) print line; close(file) }
    { print }
    /^---$/ && ++n == 2 {
      print ""
      print "<!-- Vendored from ECC (https://github.com/affaan-m/ECC) at commit " sha ", agents/" a ".md. MIT License: see LICENSE.ECC beside this file. Generated by scripts/vendor-agents.sh: edit .claude/agent-context/" a ".md and re-run it, never this file. Everything after the Repo context block is upstream verbatim. -->"
      print ""
      print "## Repo context"
      print ""
      emit(common)
      print ""
      emit(ctx)
    }
  ' "$ECC_ROOT/agents/$a.md"
}

mkdir -p "$DEST"
for a in "${agents[@]}"; do
  build "$a" >"$DEST/$a.md.tmp"
  mv "$DEST/$a.md.tmp" "$DEST/$a.md"
done
cp "$ECC_ROOT/LICENSE" "$DEST/LICENSE.ECC"

echo "Vendored ${#agents[@]} agent(s) from ECC ${sha:0:7} into $DEST/: ${agents[*]}"
echo "Review with: git diff $DEST/"
