#!/usr/bin/env bash
# Build the reviewer agents in .claude/agents/ from the ECC plugin's agents plus
# this repo's context.
#
# Why vendored: cloud sessions do not load plugins, so the reviewers that
# /work-next-item Step 6.5 launches must be committed to the repo. Each agent is
# ECC's file verbatim, frontmatter and body, with a "Repo context" block after
# the frontmatter that overrides generic advice that does not fit this repo.
#
# The agents to build are the files in .claude/agent-context/: <agent>.md holds
# that agent's context, and _common.md goes before it in every agent. To add an
# agent, add its context file (named as in ECC's agents/ directory) and re-run.
# Edit the context files, never the generated agents.
#
# The ECC commit to vendor from is pinned in scripts/ECC_PIN. The script refuses a
# checkout at any other commit, or one with uncommitted changes to what it copies,
# so a moved or tampered upstream cannot slip new reviewer prompts in unnoticed.
# To take a new upstream version, review it, then re-run with --adopt: that
# vendors from the checkout's commit and pins it.
#
# Usage (from anywhere in the repo): scripts/vendor-agents.sh [--adopt]
#   ECC_ROOT  a clone of https://github.com/affaan-m/ECC
#             (default: Claude Code's checkout of the ECC plugin)
# Then review `git diff .claude/agents/ scripts/ECC_PIN`: an upstream change
# arrives verbatim.
set -euo pipefail

ECC_ROOT="${ECC_ROOT:-$HOME/.claude/plugins/marketplaces/ecc}"
DEST=.claude/agents
CONTEXT=.claude/agent-context
COMMON="$CONTEXT/_common.md"
PIN=scripts/ECC_PIN
SHA_RE='^[0-9a-f]{40}$'
# Written into every generated agent. An agent without it was written by hand,
# so this script never overwrites or removes it.
MARKER="Generated by scripts/vendor-agents.sh"

die() { echo "vendor-agents: $*" >&2; exit 1; }

adopt=0
for arg in "$@"; do
  case "$arg" in
    --adopt) adopt=1 ;;
    *) die "unknown argument '$arg' (usage: scripts/vendor-agents.sh [--adopt])" ;;
  esac
done

root="$(git rev-parse --show-toplevel 2>/dev/null)" || die "not inside a git repository"
cd "$root"
[ -d "$ECC_ROOT/agents" ] || die "no ECC agents at $ECC_ROOT/agents (set ECC_ROOT to a clone of https://github.com/affaan-m/ECC)"
[ -f "$ECC_ROOT/LICENSE" ] || die "no LICENSE in $ECC_ROOT; vendoring needs it to ship beside the agents"
[ -f "$COMMON" ] || die "missing $COMMON"
# git looks in parent directories too: a plain copy of ECC inside some other repo
# would otherwise report that repo's commit as ECC's.
top="$(git -C "$ECC_ROOT" rev-parse --show-toplevel 2>/dev/null)" \
  && [ "$top" = "$(cd "$ECC_ROOT" && pwd -P)" ] \
  || die "$ECC_ROOT is not the top of a git checkout, so the vendored commit is unknown"
sha="$(git -C "$ECC_ROOT" rev-parse HEAD 2>/dev/null)" || die "$ECC_ROOT has no commit checked out, so the vendored commit is unknown"

# The files are read from the working tree, so they are the commit's only if
# nothing there has changed. --adopt does not lift this: it pins a commit.
dirty="$(git -C "$ECC_ROOT" status --porcelain --untracked-files=all -- agents LICENSE)" \
  || die "could not read the git status of $ECC_ROOT"
[ -z "$dirty" ] || die "$ECC_ROOT has uncommitted changes to agents/ or LICENSE, so what would be vendored is not commit $sha:
$dirty"

if [ "$adopt" -eq 0 ]; then
  [ -f "$PIN" ] || die "no $PIN, so there is no expected ECC commit. $ECC_ROOT is at $sha: once you trust that commit, re-run with --adopt to pin it"
  pinned="$(cat "$PIN")" || die "could not read $PIN"
  [[ "$pinned" =~ $SHA_RE ]] || die "$PIN must hold one full 40-character commit hash, not '$pinned'"
  [ "$pinned" = "$sha" ] || die "$ECC_ROOT is at $sha, but $PIN expects $pinned. Check out the pinned commit, or review the upstream change (git -C '$ECC_ROOT' diff $pinned $sha -- agents LICENSE) and re-run with --adopt to pin $sha"
fi

agents=()
for f in "$CONTEXT"/*.md; do
  [ -e "$f" ] || continue
  name="$(basename "$f" .md)"
  [ "$name" = _common ] || agents+=("$name")
done
[ "${#agents[@]}" -gt 0 ] || die "no agent context files in $CONTEXT (add <agent>.md for each reviewer)"

# Check every agent before writing any, so a typo cannot leave a half-updated set.
for a in "${agents[@]}"; do
  src="$ECC_ROOT/agents/$a.md"
  [ -f "$src" ] || die "ECC has no agent named '$a' (from $CONTEXT/$a.md)"
  [ "$(head -1 "$src")" = --- ] || die "$src has no frontmatter"
  # The context goes after the closing ---; without one it would silently vanish.
  awk 'NR > 1 && /^---$/ { closed = 1; exit } END { exit !closed }' "$src" \
    || die "$src never closes its frontmatter with ---"
  dest="$DEST/$a.md"
  if [ -e "$dest" ] && ! grep -qF "$MARKER" "$dest"; then
    die "$dest was not generated by this script and would be overwritten; move it aside (or delete $CONTEXT/$a.md to keep it), then re-run"
  fi
done

# Upstream file, with the attribution and context inserted after the frontmatter.
build() {
  local a="$1"
  awk -v a="$a" -v sha="$sha" -v marker="$MARKER" -v common="$COMMON" -v ctx="$CONTEXT/$a.md" '
    function emit(file,   line) { while ((getline line < file) > 0) print line; close(file) }
    { print }
    /^---$/ && ++n == 2 {
      print ""
      print "<!-- Vendored from ECC (https://github.com/affaan-m/ECC) at commit " sha ", agents/" a ".md. MIT License: see LICENSE.ECC beside this file. " marker ": edit .claude/agent-context/" a ".md and re-run it, never this file. Everything after the Repo context block is upstream verbatim. -->"
      print ""
      print "## Repo context"
      print ""
      emit(common)
      print ""
      emit(ctx)
    }
  ' "$ECC_ROOT/agents/$a.md"
}

mkdir -p "$DEST"
for a in "${agents[@]}"; do
  build "$a" >"$DEST/$a.md.tmp"
  mv "$DEST/$a.md.tmp" "$DEST/$a.md"
done
cp "$ECC_ROOT/LICENSE" "$DEST/LICENSE.ECC"

# Retire generated agents whose context file is gone: deleting the context is how
# a reviewer is removed. Hand-written agents (no marker) are left alone.
for f in "$DEST"/*.md; do
  [ -e "$f" ] || continue
  [ -f "$CONTEXT/$(basename "$f")" ] && continue
  grep -qF "$MARKER" "$f" || continue
  rm -- "$f"
  echo "Removed $f: its context file is gone"
done

# Pin last, so a run that fails part-way never moves the pin.
if [ "$adopt" -eq 1 ]; then
  echo "$sha" >"$PIN.tmp"
  mv "$PIN.tmp" "$PIN"
  echo "Pinned ECC $sha in $PIN"
fi

echo "Vendored ${#agents[@]} agent(s) from ECC ${sha:0:7} into $DEST/: ${agents[*]}"
echo "Review with: git diff $DEST/ $PIN"
